{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0af532e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !pip install pycryptodome\n",
    "# !pip install pycryptodome-test-vectors\n",
    "# !python -m Crypto.SelfTest\n",
    "# !pip install pycryptodomex\n",
    "# !pip install pycryptodome-test-vectors\n",
    "\n",
    "\n",
    "# Documentation \n",
    "#  https://pycryptodome.readthedocs.io/en/latest/src/cipher/des.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6a7a581c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from Crypto.Cipher import DES\n",
    "from secrets import token_bytes\n",
    "\n",
    "\n",
    "\n",
    "def encrypt_double_des(msg , key1,key2):\n",
    "    nonce ,ciphertext ,tag = encrypt(msg,key1)\n",
    "    print(\"Nonce :{}\\nCipherText : {}\\n tag : {}\".format(nonce ,ciphertext ,tag))\n",
    "    \n",
    "    \n",
    "def encrypt(msg,key):\n",
    "    \n",
    "    cipher = DES.new(key,DES.MODE_EAX)\n",
    "    nonce = cipher.nonce\n",
    "    \n",
    "    ciphertext , tag = cipher.encrypt_and_digest(msg.encode(\"ascii\"))\n",
    "    \n",
    "    return nonce ,ciphertext ,tag\n",
    "\n",
    "# def decrypt(nonce , ciphertext , tag):\n",
    "    \n",
    "#     cipher = DES.new(key,DES.MODE_EAX , nonce = nonce)\n",
    "#     plaintext = cipher.decrypt(ciphertext)\n",
    "    \n",
    "#     try:\n",
    "#         cipher.verify(tag)\n",
    "#         return plaintext.decode('ascii')\n",
    "#     except :\n",
    "#         return False\n",
    "    \n",
    "if __name__ == '__main__':\n",
    "    \n",
    "    key1 = token_bytes(8)\n",
    "    key2 = token_bytes(8)\n",
    "\n",
    "    nonce, ciphertext, tag = encrypt_double_des(\"iftikhar\",key1,key2)\n",
    "#     plaintext = decrypt(nonce ,ciphertext,tag)\n",
    "    \n",
    "    print(\"Cipher Text : {}\".format(ciphertext))\n",
    "    \n",
    "if not plaintext:\n",
    "    print(\"Message is corrupted\")\n",
    "else:\n",
    "    print(\"Plain Text : {}\".format(plaintext))\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12e49157",
   "metadata": {},
   "outputs": [],
   "source": [
    "token_bytes?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b5b54c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python\n",
    "import binascii\n",
    "import itertools\n",
    "from pyDes import des\n",
    "from pyDes import CBC\n",
    "import sys\n",
    "\n",
    "# Our IV is 5edcc504\n",
    "\n",
    "# Instructions\n",
    "# * Use the skeleton code provided here.\n",
    "# * Use the DES library as shown in twodes.py\n",
    "# * Use binascii's (un)hexlify to convert between bytes and hex\n",
    "#   representation. We do not care if you do your comparisons on bytes\n",
    "#   or hex - in our sample solution we have chosen hex for better\n",
    "#   readability of debugging output. The only thing we require is that\n",
    "#   the \"ciphertext\" input to lookupInTable() is in hex.\n",
    "# * In your final solution, your last two lines that you print to the\n",
    "#   screen MUST be the output of lookupInTable, exactly in the format\n",
    "#   indicated!\n",
    "\n",
    "# The following is your plaintext/ciphertext pair. We read it from \n",
    "# stdin:\n",
    "plaintext = sys.argv[1]\n",
    "ciphertext = sys.argv[2]\n",
    "\n",
    "# Read in the effective keylength in number of hex digits. This value\n",
    "# is either 3 or 4 in our case:\n",
    "effKeyLength = int(sys.argv[3])\n",
    "\n",
    "#Default IV as defined\n",
    "iv='5edcc504'\n",
    "\n",
    "#default pad 16 hex digit\n",
    "def_pad=\"0000000000000000\"\n",
    "\n",
    "#the function handed to us to get the decryption done\n",
    "def twodes(plain, keyOne, keyTwo):\n",
    "    cipherOne = des(binascii.unhexlify(keyOne), CBC, \"5edcc504\", pad=None)\n",
    "    cipherTwo = des(binascii.unhexlify(keyTwo), CBC, \"5edcc504\", pad=None)\n",
    "    return cipherTwo.encrypt(cipherOne.encrypt(plain))\n",
    "\n",
    "#This function generates and returns the total number of keys that could have been used\n",
    "def generatePermutation():\n",
    "    t=[\"\".join(seq) for seq in itertools.product(\"0123456789abcdef\", repeat=effKeyLength)]\n",
    "    for x in t:\n",
    "        yield x\n",
    "\n",
    "#function to check and give the corrct padding\n",
    "def checkPad(effKeyLength):\n",
    "    if(effKeyLength > 4):\n",
    "        #since the test scope is out of the condition print the warning\n",
    "        print 'Key Length greater than 4 will take much time'\n",
    "    return def_pad[0:-(effKeyLength)]\n",
    "\n",
    "# Generate the \"forward\" table\n",
    "# Input: plaintext in hex, effective key length in hex digits \n",
    "# (3 or 4, see above)\n",
    "# Don't forget to use the IV (see above)\n",
    "# Output: a representation of the forward table\n",
    "def generateTable(plaintext, effKeyLength):\n",
    "    #Call generate Permutation to yield all the possible combinations of key length\n",
    "    perms=generatePermutation();\n",
    "    #Check for the correct padding accoding to keylength\n",
    "    pad=checkPad(effKeyLength);\n",
    "    #initialize the dictionary to hold the values\n",
    "    enctable={}    \n",
    "    #Loop thorugh all possible keys\n",
    "    for p in perms:\n",
    "        #pad the possible keys to make it 16 Hex digit\n",
    "        p=pad+p\n",
    "        if(len(p) != 16):\n",
    "            #Some logic has gone wrong\n",
    "            print \"padding gone wrong...\"\n",
    "        #Initate the key for single DES encryption\n",
    "        k1 = des(binascii.unhexlify(p), CBC, \"5edcc504\", pad=None)\n",
    "        #yield p+\":\"+binascii.hexlify(k1.encrypt(plaintext))\n",
    "        \n",
    "        #store the key, value pair for further inspection\n",
    "        enctable[p]=binascii.hexlify(k1.encrypt(plaintext))\n",
    "    return enctable\n",
    "\n",
    "#return true if the guessed key pair gives correct ciphertext for the plaintext\n",
    "def checkCipher(x, p):\n",
    "    #Call the twodes function to check if the ciphertext is produced by the guess key values\n",
    "    if(ciphertext==binascii.hexlify(twodes(plaintext,x,p))):\n",
    "        return True\n",
    "    return False\n",
    "    \n",
    "\n",
    "\n",
    "# Do the lookups.\n",
    "# Input:\n",
    "# * the representation of your forward table\n",
    "# * the ciphertext as hex representation\n",
    "# * the effective key length\n",
    "# Don't forget to use the IV if you do crypto here (see above)\n",
    "# Output:\n",
    "# Key 1, Key 2 in *exactly* the format as below\n",
    "def lookupInTable(enctable, ciphertext, effKeyLength):\n",
    "    #the return variables\n",
    "    key1,key2=\"\",\"\"\n",
    "    #repeat the first initialization step as in encryption\n",
    "    #Call generate Permutation to yield all the possible combinations of key length\n",
    "    perms2=generatePermutation();\n",
    "    #Check padding\n",
    "    pad=checkPad(effKeyLength)\n",
    "    #Set the flag false for matched keys\n",
    "    flag= False\n",
    "    for p in perms2:\n",
    "        #pad the possible keys to make it 16 Hex digit\n",
    "        p=pad+p\n",
    "        if(len(p) != 16):\n",
    "            #Some logic has gone wrong\n",
    "            print \"padding gone wrong...\"\n",
    "            return\n",
    "        #Initialize the key for decryption\n",
    "        k2 =  des(binascii.unhexlify(p), CBC, \"5edcc504\", pad=None)\n",
    "        #decrypt the ciphertext\n",
    "        pt=binascii.hexlify(k2.decrypt(binascii.unhexlify(ciphertext)))\n",
    "\n",
    "        #Loop through lookup table\n",
    "        for x in enctable:\n",
    "            if (enctable[x]==pt):\n",
    "                #If match is found do the final check for ciphertext and keypairs\n",
    "                if checkCipher(x,p):\n",
    "                    #Set the flag true,assing the keys, break the loop\n",
    "                    flag=True\n",
    "                    key1=x\n",
    "                    key2=p\n",
    "                    break\n",
    "        #since the task is done break the loop\n",
    "        if flag:\n",
    "            break\n",
    "    print \"Key1:\" + key1\n",
    "    print \"Key2:\" + key2\n",
    "\n",
    "#Start of main function\n",
    "def main():\n",
    "    enctable = generateTable(plaintext,effKeyLength)\n",
    "    lookupInTable(enctable, ciphertext, effKeyLength)\n",
    "\n",
    "main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7110b16",
   "metadata": {},
   "outputs": [],
   "source": [
    " #############################################################################\n",
    "    # \t\t\t\tDocumentation\t\t\t\t    #\n",
    "    #############################################################################\n",
    "\n",
    "    # Author:   Todd Whiteman\n",
    "    # Date:     16th March, 2009\n",
    "    # Verion:   2.0.0\n",
    "    # License:  Public Domain - free to do as you wish\n",
    "    # Homepage: http://twhiteman.netfirms.com/des.html\n",
    "    #\n",
    "    # This is a pure python implementation of the DES encryption algorithm.\n",
    "    # It's pure python to avoid portability issues, since most DES \n",
    "    # implementations are programmed in C (for performance reasons).\n",
    "    #\n",
    "    # Triple DES class is also implemented, utilising the DES base. Triple DES\n",
    "    # is either DES-EDE3 with a 24 byte key, or DES-EDE2 with a 16 byte key.\n",
    "    #\n",
    "    # See the README.txt that should come with this python module for the\n",
    "    # implementation methods used.\n",
    "    #\n",
    "    # Thanks to:\n",
    "    #  * David Broadwell for ideas, comments and suggestions.\n",
    "    #  * Mario Wolff for pointing out and debugging some triple des CBC errors.\n",
    "    #  * Santiago Palladino for providing the PKCS5 padding technique.\n",
    "    #  * Shaya for correcting the PAD_PKCS5 triple des CBC errors.\n",
    "    #\n",
    "    \"\"\"A pure python implementation of the DES and TRIPLE DES encryption algorithms.\n",
    "\n",
    "    Class initialization\n",
    "    --------------------\n",
    "    pyDes.des(key, [mode], [IV], [pad], [padmode])\n",
    "    pyDes.triple_des(key, [mode], [IV], [pad], [padmode])\n",
    "\n",
    "    key     -> Bytes containing the encryption key. 8 bytes for DES, 16 or 24 bytes\n",
    "       for Triple DES\n",
    "    mode    -> Optional argument for encryption type, can be either\n",
    "       pyDes.ECB (Electronic Code Book) or pyDes.CBC (Cypher Block Chaining)\n",
    "    IV      -> Optional Initial Value bytes, must be supplied if using CBC mode.\n",
    "       Length must be 8 bytes.\n",
    "    pad     -> Optional argument, set the pad character (PAD_NORMAL) to use during\n",
    "       all encrypt/decrpt operations done with this instance.\n",
    "    padmode -> Optional argument, set the padding mode (PAD_NORMAL or PAD_PKCS5)\n",
    "       to use during all encrypt/decrpt operations done with this instance.\n",
    "\n",
    "    I recommend to use PAD_PKCS5 padding, as then you never need to worry about any\n",
    "    padding issues, as the padding can be removed unambiguously upon decrypting\n",
    "    data that was encrypted using PAD_PKCS5 padmode.\n",
    "\n",
    "    Common methods\n",
    "    --------------\n",
    "    encrypt(data, [pad], [padmode])\n",
    "    decrypt(data, [pad], [padmode])\n",
    "\n",
    "    data    -> Bytes to be encrypted/decrypted\n",
    "    pad     -> Optional argument. Only when using padmode of PAD_NORMAL. For\n",
    "       encryption, adds this characters to the end of the data block when\n",
    "       data is not a multiple of 8 bytes. For decryption, will remove the\n",
    "       trailing characters that match this pad character from the last 8\n",
    "       bytes of the unencrypted data block.\n",
    "    padmode -> Optional argument, set the padding mode, must be one of PAD_NORMAL\n",
    "       or PAD_PKCS5). Defaults to PAD_NORMAL.\n",
    "\n",
    "\n",
    "    Example\n",
    "    -------\n",
    "    from pyDes import *\n",
    "\n",
    "    data = \"Please encrypt my data\"\n",
    "    k = des(\"DESCRYPT\", CBC, \"\\0\\0\\0\\0\\0\\0\\0\\0\", pad=None, padmode=PAD_PKCS5)\n",
    "    # For Python3, you'll need to use bytes, i.e.:\n",
    "    #   data = b\"Please encrypt my data\"\n",
    "    #   k = des(b\"DESCRYPT\", CBC, b\"\\0\\0\\0\\0\\0\\0\\0\\0\", pad=None, padmode=PAD_PKCS5)\n",
    "    d = k.encrypt(data)\n",
    "    print \"Encrypted: %r\" % d\n",
    "    print \"Decrypted: %r\" % k.decrypt(d)\n",
    "    assert k.decrypt(d, padmode=PAD_PKCS5) == data\n",
    "\n",
    "\n",
    "    See the module source (pyDes.py) for more examples of use.\n",
    "    You can also run the pyDes.py file without and arguments to see a simple test.\n",
    "\n",
    "    Note: This code was not written for high-end systems needing a fast\n",
    "      implementation, but rather a handy portable solution with small usage.\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "    import sys\n",
    "\n",
    "    # _pythonMajorVersion is used to handle Python2 and Python3 differences.\n",
    "    _pythonMajorVersion = sys.version_info[0]\n",
    "\n",
    "    # Modes of crypting / cyphering\n",
    "    ECB =\t0\n",
    "    CBC =\t1\n",
    "\n",
    "    # Modes of padding\n",
    "    PAD_NORMAL = 1\n",
    "    PAD_PKCS5 = 2\n",
    "\n",
    "    # PAD_PKCS5: is a method that will unambiguously remove all padding\n",
    "    #            characters after decryption, when originally encrypted with\n",
    "    #            this padding mode.\n",
    "    # For a good description of the PKCS5 padding technique, see:\n",
    "    # http://www.faqs.org/rfcs/rfc1423.html\n",
    "\n",
    "    # The base class shared by des and triple des.\n",
    "    class _baseDes(object):\n",
    "    def __init__(self, mode=ECB, IV=None, pad=None, padmode=PAD_NORMAL):\n",
    "        if IV:\n",
    "            IV = self._guardAgainstUnicode(IV)\n",
    "        if pad:\n",
    "            pad = self._guardAgainstUnicode(pad)\n",
    "        self.block_size = 8\n",
    "        # Sanity checking of arguments.\n",
    "        if pad and padmode == PAD_PKCS5:\n",
    "            raise ValueError(\"Cannot use a pad character with PAD_PKCS5\")\n",
    "        if IV and len(IV) != self.block_size:\n",
    "            raise ValueError(\"Invalid Initial Value (IV), must be a multiple of \" + str(self.block_size) + \" bytes\")\n",
    "\n",
    "        # Set the passed in variables\n",
    "        self._mode = mode\n",
    "        self._iv = IV\n",
    "        self._padding = pad\n",
    "        self._padmode = padmode\n",
    "\n",
    "    def getKey(self):\n",
    "        \"\"\"getKey() -> bytes\"\"\"\n",
    "        return self.__key\n",
    "\n",
    "    def setKey(self, key):\n",
    "        \"\"\"Will set the crypting key for this object.\"\"\"\n",
    "        key = self._guardAgainstUnicode(key)\n",
    "        self.__key = key\n",
    "\n",
    "    def getMode(self):\n",
    "        \"\"\"getMode() -> pyDes.ECB or pyDes.CBC\"\"\"\n",
    "        return self._mode\n",
    "\n",
    "    def setMode(self, mode):\n",
    "        \"\"\"Sets the type of crypting mode, pyDes.ECB or pyDes.CBC\"\"\"\n",
    "        self._mode = mode\n",
    "\n",
    "    def getPadding(self):\n",
    "        \"\"\"getPadding() -> bytes of length 1. Padding character.\"\"\"\n",
    "        return self._padding\n",
    "\n",
    "    def setPadding(self, pad):\n",
    "        \"\"\"setPadding() -> bytes of length 1. Padding character.\"\"\"\n",
    "        if pad is not None:\n",
    "            pad = self._guardAgainstUnicode(pad)\n",
    "        self._padding = pad\n",
    "\n",
    "    def getPadMode(self):\n",
    "        \"\"\"getPadMode() -> pyDes.PAD_NORMAL or pyDes.PAD_PKCS5\"\"\"\n",
    "        return self._padmode\n",
    "\n",
    "    def setPadMode(self, mode):\n",
    "        \"\"\"Sets the type of padding mode, pyDes.PAD_NORMAL or pyDes.PAD_PKCS5\"\"\"\n",
    "        self._padmode = mode\n",
    "\n",
    "    def getIV(self):\n",
    "        \"\"\"getIV() -> bytes\"\"\"\n",
    "        return self._iv\n",
    "\n",
    "    def setIV(self, IV):\n",
    "        \"\"\"Will set the Initial Value, used in conjunction with CBC mode\"\"\"\n",
    "        if not IV or len(IV) != self.block_size:\n",
    "            raise ValueError(\"Invalid Initial Value (IV), must be a multiple of \" + str(self.block_size) + \" bytes\")\n",
    "        IV = self._guardAgainstUnicode(IV)\n",
    "        self._iv = IV\n",
    "\n",
    "    def _padData(self, data, pad, padmode):\n",
    "        # Pad data depending on the mode\n",
    "        if padmode is None:\n",
    "            # Get the default padding mode.\n",
    "            padmode = self.getPadMode()\n",
    "        if pad and padmode == PAD_PKCS5:\n",
    "            raise ValueError(\"Cannot use a pad character with PAD_PKCS5\")\n",
    "\n",
    "        if padmode == PAD_NORMAL:\n",
    "            if len(data) % self.block_size == 0:\n",
    "                # No padding required.\n",
    "                return data\n",
    "\n",
    "            if not pad:\n",
    "                # Get the default padding.\n",
    "                pad = self.getPadding()\n",
    "            if not pad:\n",
    "                raise ValueError(\"Data must be a multiple of \" + str(self.block_size) + \" bytes in length. Use padmode=PAD_PKCS5 or set the pad character.\")\n",
    "            data += (self.block_size - (len(data) % self.block_size)) * pad\n",
    "\n",
    "        elif padmode == PAD_PKCS5:\n",
    "            pad_len = 8 - (len(data) % self.block_size)\n",
    "            if _pythonMajorVersion < 3:\n",
    "                data += pad_len * chr(pad_len)\n",
    "            else:\n",
    "                data += bytes([pad_len] * pad_len)\n",
    "\n",
    "        return data\n",
    "\n",
    "    def _unpadData(self, data, pad, padmode):\n",
    "        # Unpad data depending on the mode.\n",
    "        if not data:\n",
    "            return data\n",
    "        if pad and padmode == PAD_PKCS5:\n",
    "            raise ValueError(\"Cannot use a pad character with PAD_PKCS5\")\n",
    "        if padmode is None:\n",
    "            # Get the default padding mode.\n",
    "            padmode = self.getPadMode()\n",
    "\n",
    "        if padmode == PAD_NORMAL:\n",
    "            if not pad:\n",
    "                # Get the default padding.\n",
    "                pad = self.getPadding()\n",
    "            if pad:\n",
    "                data = data[:-self.block_size] + \\\n",
    "                       data[-self.block_size:].rstrip(pad)\n",
    "\n",
    "        elif padmode == PAD_PKCS5:\n",
    "            if _pythonMajorVersion < 3:\n",
    "                pad_len = ord(data[-1])\n",
    "            else:\n",
    "                pad_len = data[-1]\n",
    "            data = data[:-pad_len]\n",
    "\n",
    "        return data\n",
    "\n",
    "    def _guardAgainstUnicode(self, data):\n",
    "        # Only accept byte strings or ascii unicode values, otherwise\n",
    "        # there is no way to correctly decode the data into bytes.\n",
    "        if _pythonMajorVersion < 3:\n",
    "            if isinstance(data, unicode):\n",
    "                raise ValueError(\"pyDes can only work with bytes, not Unicode strings.\")\n",
    "        else:\n",
    "            if isinstance(data, str):\n",
    "                # Only accept ascii unicode values.\n",
    "                try:\n",
    "                    return data.encode('ascii')\n",
    "                except UnicodeEncodeError:\n",
    "                    pass\n",
    "                raise ValueError(\"pyDes can only work with encoded strings, not Unicode.\")\n",
    "        return data\n",
    "\n",
    "    #############################################################################\n",
    "    # \t\t\t\t    DES\t\t\t\t\t    #\n",
    "    #############################################################################\n",
    "    class des(_baseDes):\n",
    "    \"\"\"DES encryption/decrytpion class\n",
    "\n",
    "    Supports ECB (Electronic Code Book) and CBC (Cypher Block Chaining) modes.\n",
    "\n",
    "    pyDes.des(key,[mode], [IV])\n",
    "\n",
    "    key  -> Bytes containing the encryption key, must be exactly 8 bytes\n",
    "    mode -> Optional argument for encryption type, can be either pyDes.ECB\n",
    "        (Electronic Code Book), pyDes.CBC (Cypher Block Chaining)\n",
    "    IV   -> Optional Initial Value bytes, must be supplied if using CBC mode.\n",
    "        Must be 8 bytes in length.\n",
    "    pad  -> Optional argument, set the pad character (PAD_NORMAL) to use\n",
    "        during all encrypt/decrpt operations done with this instance.\n",
    "    padmode -> Optional argument, set the padding mode (PAD_NORMAL or\n",
    "        PAD_PKCS5) to use during all encrypt/decrpt operations done\n",
    "        with this instance.\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "    # Permutation and translation tables for DES\n",
    "    __pc1 = [56, 48, 40, 32, 24, 16,  8,\n",
    "          0, 57, 49, 41, 33, 25, 17,\n",
    "          9,  1, 58, 50, 42, 34, 26,\n",
    "         18, 10,  2, 59, 51, 43, 35,\n",
    "         62, 54, 46, 38, 30, 22, 14,\n",
    "          6, 61, 53, 45, 37, 29, 21,\n",
    "         13,  5, 60, 52, 44, 36, 28,\n",
    "         20, 12,  4, 27, 19, 11,  3\n",
    "    ]\n",
    "\n",
    "    # number left rotations of pc1\n",
    "    __left_rotations = [\n",
    "        1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1\n",
    "    ]\n",
    "\n",
    "    # permuted choice key (table 2)\n",
    "    __pc2 = [\n",
    "        13, 16, 10, 23,  0,  4,\n",
    "         2, 27, 14,  5, 20,  9,\n",
    "        22, 18, 11,  3, 25,  7,\n",
    "        15,  6, 26, 19, 12,  1,\n",
    "        40, 51, 30, 36, 46, 54,\n",
    "        29, 39, 50, 44, 32, 47,\n",
    "        43, 48, 38, 55, 33, 52,\n",
    "        45, 41, 49, 35, 28, 31\n",
    "    ]\n",
    "\n",
    "    # initial permutation IP\n",
    "    __ip = [57, 49, 41, 33, 25, 17, 9,  1,\n",
    "        59, 51, 43, 35, 27, 19, 11, 3,\n",
    "        61, 53, 45, 37, 29, 21, 13, 5,\n",
    "        63, 55, 47, 39, 31, 23, 15, 7,\n",
    "        56, 48, 40, 32, 24, 16, 8,  0,\n",
    "        58, 50, 42, 34, 26, 18, 10, 2,\n",
    "        60, 52, 44, 36, 28, 20, 12, 4,\n",
    "        62, 54, 46, 38, 30, 22, 14, 6\n",
    "    ]\n",
    "\n",
    "    # Expansion table for turning 32 bit blocks into 48 bits\n",
    "    __expansion_table = [\n",
    "        31,  0,  1,  2,  3,  4,\n",
    "         3,  4,  5,  6,  7,  8,\n",
    "         7,  8,  9, 10, 11, 12,\n",
    "        11, 12, 13, 14, 15, 16,\n",
    "        15, 16, 17, 18, 19, 20,\n",
    "        19, 20, 21, 22, 23, 24,\n",
    "        23, 24, 25, 26, 27, 28,\n",
    "        27, 28, 29, 30, 31,  0\n",
    "    ]\n",
    "\n",
    "    # The (in)famous S-boxes\n",
    "    __sbox = [\n",
    "        # S1\n",
    "        [14, 4, 13, 1, 2, 15, 11, 8, 3, 10, 6, 12, 5, 9, 0, 7,\n",
    "         0, 15, 7, 4, 14, 2, 13, 1, 10, 6, 12, 11, 9, 5, 3, 8,\n",
    "         4, 1, 14, 8, 13, 6, 2, 11, 15, 12, 9, 7, 3, 10, 5, 0,\n",
    "         15, 12, 8, 2, 4, 9, 1, 7, 5, 11, 3, 14, 10, 0, 6, 13],\n",
    "\n",
    "        # S2\n",
    "        [15, 1, 8, 14, 6, 11, 3, 4, 9, 7, 2, 13, 12, 0, 5, 10,\n",
    "         3, 13, 4, 7, 15, 2, 8, 14, 12, 0, 1, 10, 6, 9, 11, 5,\n",
    "         0, 14, 7, 11, 10, 4, 13, 1, 5, 8, 12, 6, 9, 3, 2, 15,\n",
    "         13, 8, 10, 1, 3, 15, 4, 2, 11, 6, 7, 12, 0, 5, 14, 9],\n",
    "\n",
    "        # S3\n",
    "        [10, 0, 9, 14, 6, 3, 15, 5, 1, 13, 12, 7, 11, 4, 2, 8,\n",
    "         13, 7, 0, 9, 3, 4, 6, 10, 2, 8, 5, 14, 12, 11, 15, 1,\n",
    "         13, 6, 4, 9, 8, 15, 3, 0, 11, 1, 2, 12, 5, 10, 14, 7,\n",
    "         1, 10, 13, 0, 6, 9, 8, 7, 4, 15, 14, 3, 11, 5, 2, 12],\n",
    "\n",
    "        # S4\n",
    "        [7, 13, 14, 3, 0, 6, 9, 10, 1, 2, 8, 5, 11, 12, 4, 15,\n",
    "         13, 8, 11, 5, 6, 15, 0, 3, 4, 7, 2, 12, 1, 10, 14, 9,\n",
    "         10, 6, 9, 0, 12, 11, 7, 13, 15, 1, 3, 14, 5, 2, 8, 4,\n",
    "         3, 15, 0, 6, 10, 1, 13, 8, 9, 4, 5, 11, 12, 7, 2, 14],\n",
    "\n",
    "        # S5\n",
    "        [2, 12, 4, 1, 7, 10, 11, 6, 8, 5, 3, 15, 13, 0, 14, 9,\n",
    "         14, 11, 2, 12, 4, 7, 13, 1, 5, 0, 15, 10, 3, 9, 8, 6,\n",
    "         4, 2, 1, 11, 10, 13, 7, 8, 15, 9, 12, 5, 6, 3, 0, 14,\n",
    "         11, 8, 12, 7, 1, 14, 2, 13, 6, 15, 0, 9, 10, 4, 5, 3],\n",
    "\n",
    "        # S6\n",
    "        [12, 1, 10, 15, 9, 2, 6, 8, 0, 13, 3, 4, 14, 7, 5, 11,\n",
    "         10, 15, 4, 2, 7, 12, 9, 5, 6, 1, 13, 14, 0, 11, 3, 8,\n",
    "         9, 14, 15, 5, 2, 8, 12, 3, 7, 0, 4, 10, 1, 13, 11, 6,\n",
    "         4, 3, 2, 12, 9, 5, 15, 10, 11, 14, 1, 7, 6, 0, 8, 13],\n",
    "\n",
    "        # S7\n",
    "        [4, 11, 2, 14, 15, 0, 8, 13, 3, 12, 9, 7, 5, 10, 6, 1,\n",
    "         13, 0, 11, 7, 4, 9, 1, 10, 14, 3, 5, 12, 2, 15, 8, 6,\n",
    "         1, 4, 11, 13, 12, 3, 7, 14, 10, 15, 6, 8, 0, 5, 9, 2,\n",
    "         6, 11, 13, 8, 1, 4, 10, 7, 9, 5, 0, 15, 14, 2, 3, 12],\n",
    "\n",
    "        # S8\n",
    "        [13, 2, 8, 4, 6, 15, 11, 1, 10, 9, 3, 14, 5, 0, 12, 7,\n",
    "         1, 15, 13, 8, 10, 3, 7, 4, 12, 5, 6, 11, 0, 14, 9, 2,\n",
    "         7, 11, 4, 1, 9, 12, 14, 2, 0, 6, 10, 13, 15, 3, 5, 8,\n",
    "         2, 1, 14, 7, 4, 10, 8, 13, 15, 12, 9, 0, 3, 5, 6, 11],\n",
    "    ]\n",
    "\n",
    "\n",
    "    # 32-bit permutation function P used on the output of the S-boxes\n",
    "    __p = [\n",
    "        15, 6, 19, 20, 28, 11,\n",
    "        27, 16, 0, 14, 22, 25,\n",
    "        4, 17, 30, 9, 1, 7,\n",
    "        23,13, 31, 26, 2, 8,\n",
    "        18, 12, 29, 5, 21, 10,\n",
    "        3, 24\n",
    "    ]\n",
    "\n",
    "    # final permutation IP^-1\n",
    "    __fp = [\n",
    "        39,  7, 47, 15, 55, 23, 63, 31,\n",
    "        38,  6, 46, 14, 54, 22, 62, 30,\n",
    "        37,  5, 45, 13, 53, 21, 61, 29,\n",
    "        36,  4, 44, 12, 52, 20, 60, 28,\n",
    "        35,  3, 43, 11, 51, 19, 59, 27,\n",
    "        34,  2, 42, 10, 50, 18, 58, 26,\n",
    "        33,  1, 41,  9, 49, 17, 57, 25,\n",
    "        32,  0, 40,  8, 48, 16, 56, 24\n",
    "    ]\n",
    "\n",
    "    # Type of crypting being done\n",
    "    ENCRYPT =\t0x00\n",
    "    DECRYPT =\t0x01\n",
    "\n",
    "    # Initialisation\n",
    "    def __init__(self, key, mode=ECB, IV=None, pad=None, padmode=PAD_NORMAL):\n",
    "        # Sanity checking of arguments.\n",
    "        if len(key) != 8:\n",
    "            raise ValueError(\"Invalid DES key size. Key must be exactly 8 bytes long.\")\n",
    "        _baseDes.__init__(self, mode, IV, pad, padmode)\n",
    "        self.key_size = 8\n",
    "\n",
    "        self.L = []\n",
    "        self.R = []\n",
    "        self.Kn = [ [0] * 48 ] * 16\t# 16 48-bit keys (K1 - K16)\n",
    "        self.final = []\n",
    "\n",
    "        self.setKey(key)\n",
    "\n",
    "    def setKey(self, key):\n",
    "        \"\"\"Will set the crypting key for this object. Must be 8 bytes.\"\"\"\n",
    "        _baseDes.setKey(self, key)\n",
    "        self.__create_sub_keys()\n",
    "\n",
    "    def __String_to_BitList(self, data):\n",
    "        \"\"\"Turn the string data, into a list of bits (1, 0)'s\"\"\"\n",
    "        if _pythonMajorVersion < 3:\n",
    "            # Turn the strings into integers. Python 3 uses a bytes\n",
    "            # class, which already has this behaviour.\n",
    "            data = [ord(c) for c in data]\n",
    "        l = len(data) * 8\n",
    "        result = [0] * l\n",
    "        pos = 0\n",
    "        for ch in data:\n",
    "            i = 7\n",
    "            while i >= 0:\n",
    "                if ch & (1 << i) != 0:\n",
    "                    result[pos] = 1\n",
    "                else:\n",
    "                    result[pos] = 0\n",
    "                pos += 1\n",
    "                i -= 1\n",
    "\n",
    "        return result\n",
    "\n",
    "    def __BitList_to_String(self, data):\n",
    "        \"\"\"Turn the list of bits -> data, into a string\"\"\"\n",
    "        result = []\n",
    "        pos = 0\n",
    "        c = 0\n",
    "        while pos < len(data):\n",
    "            c += data[pos] << (7 - (pos % 8))\n",
    "            if (pos % 8) == 7:\n",
    "                result.append(c)\n",
    "                c = 0\n",
    "            pos += 1\n",
    "\n",
    "        if _pythonMajorVersion < 3:\n",
    "            return ''.join([ chr(c) for c in result ])\n",
    "        else:\n",
    "            return bytes(result)\n",
    "\n",
    "    def __permutate(self, table, block):\n",
    "        \"\"\"Permutate this block with the specified table\"\"\"\n",
    "        return list(map(lambda x: block[x], table))\n",
    "\n",
    "    # Transform the secret key, so that it is ready for data processing\n",
    "    # Create the 16 subkeys, K[1] - K[16]\n",
    "    def __create_sub_keys(self):\n",
    "        \"\"\"Create the 16 subkeys K[1] to K[16] from the given key\"\"\"\n",
    "        key = self.__permutate(des.__pc1, self.__String_to_BitList(self.getKey()))\n",
    "        i = 0\n",
    "        # Split into Left and Right sections\n",
    "        self.L = key[:28]\n",
    "        self.R = key[28:]\n",
    "        while i < 16:\n",
    "            j = 0\n",
    "            # Perform circular left shifts\n",
    "            while j < des.__left_rotations[i]:\n",
    "                self.L.append(self.L[0])\n",
    "                del self.L[0]\n",
    "\n",
    "                self.R.append(self.R[0])\n",
    "                del self.R[0]\n",
    "\n",
    "                j += 1\n",
    "\n",
    "            # Create one of the 16 subkeys through pc2 permutation\n",
    "            self.Kn[i] = self.__permutate(des.__pc2, self.L + self.R)\n",
    "\n",
    "            i += 1\n",
    "\n",
    "    # Main part of the encryption algorithm, the number cruncher :)\n",
    "    def __des_crypt(self, block, crypt_type):\n",
    "        \"\"\"Crypt the block of data through DES bit-manipulation\"\"\"\n",
    "        block = self.__permutate(des.__ip, block)\n",
    "        self.L = block[:32]\n",
    "        self.R = block[32:]\n",
    "\n",
    "        # Encryption starts from Kn[1] through to Kn[16]\n",
    "        if crypt_type == des.ENCRYPT:\n",
    "            iteration = 0\n",
    "            iteration_adjustment = 1\n",
    "        # Decryption starts from Kn[16] down to Kn[1]\n",
    "        else:\n",
    "            iteration = 15\n",
    "            iteration_adjustment = -1\n",
    "\n",
    "        i = 0\n",
    "        while i < 16:\n",
    "            # Make a copy of R[i-1], this will later become L[i]\n",
    "            tempR = self.R[:]\n",
    "\n",
    "            # Permutate R[i - 1] to start creating R[i]\n",
    "            self.R = self.__permutate(des.__expansion_table, self.R)\n",
    "\n",
    "            # Exclusive or R[i - 1] with K[i], create B[1] to B[8] whilst here\n",
    "            self.R = list(map(lambda x, y: x ^ y, self.R, self.Kn[iteration]))\n",
    "            B = [self.R[:6], self.R[6:12], self.R[12:18], self.R[18:24], self.R[24:30], self.R[30:36], self.R[36:42], self.R[42:]]\n",
    "            # Optimization: Replaced below commented code with above\n",
    "            #j = 0\n",
    "            #B = []\n",
    "            #while j < len(self.R):\n",
    "            #\tself.R[j] = self.R[j] ^ self.Kn[iteration][j]\n",
    "            #\tj += 1\n",
    "            #\tif j % 6 == 0:\n",
    "            #\t\tB.append(self.R[j-6:j])\n",
    "\n",
    "            # Permutate B[1] to B[8] using the S-Boxes\n",
    "            j = 0\n",
    "            Bn = [0] * 32\n",
    "            pos = 0\n",
    "            while j < 8:\n",
    "                # Work out the offsets\n",
    "                m = (B[j][0] << 1) + B[j][5]\n",
    "                n = (B[j][1] << 3) + (B[j][2] << 2) + (B[j][3] << 1) + B[j][4]\n",
    "\n",
    "                # Find the permutation value\n",
    "                v = des.__sbox[j][(m << 4) + n]\n",
    "\n",
    "                # Turn value into bits, add it to result: Bn\n",
    "                Bn[pos] = (v & 8) >> 3\n",
    "                Bn[pos + 1] = (v & 4) >> 2\n",
    "                Bn[pos + 2] = (v & 2) >> 1\n",
    "                Bn[pos + 3] = v & 1\n",
    "\n",
    "                pos += 4\n",
    "                j += 1\n",
    "\n",
    "            # Permutate the concatination of B[1] to B[8] (Bn)\n",
    "            self.R = self.__permutate(des.__p, Bn)\n",
    "\n",
    "            # Xor with L[i - 1]\n",
    "            self.R = list(map(lambda x, y: x ^ y, self.R, self.L))\n",
    "            # Optimization: This now replaces the below commented code\n",
    "            #j = 0\n",
    "            #while j < len(self.R):\n",
    "            #\tself.R[j] = self.R[j] ^ self.L[j]\n",
    "            #\tj += 1\n",
    "\n",
    "            # L[i] becomes R[i - 1]\n",
    "            self.L = tempR\n",
    "\n",
    "            i += 1\n",
    "            iteration += iteration_adjustment\n",
    "\n",
    "        # Final permutation of R[16]L[16]\n",
    "        self.final = self.__permutate(des.__fp, self.R + self.L)\n",
    "        return self.final\n",
    "\n",
    "\n",
    "    # Data to be encrypted/decrypted\n",
    "    def crypt(self, data, crypt_type):\n",
    "        \"\"\"Crypt the data in blocks, running it through des_crypt()\"\"\"\n",
    "\n",
    "        # Error check the data\n",
    "        if not data:\n",
    "            return ''\n",
    "        if len(data) % self.block_size != 0:\n",
    "            if crypt_type == des.DECRYPT: # Decryption must work on 8 byte blocks\n",
    "                raise ValueError(\"Invalid data length, data must be a multiple of \" + str(self.block_size) + \" bytes\\n.\")\n",
    "            if not self.getPadding():\n",
    "                raise ValueError(\"Invalid data length, data must be a multiple of \" + str(self.block_size) + \" bytes\\n. Try setting the optional padding character\")\n",
    "            else:\n",
    "                data += (self.block_size - (len(data) % self.block_size)) * self.getPadding()\n",
    "            # print \"Len of data: %f\" % (len(data) / self.block_size)\n",
    "\n",
    "        if self.getMode() == CBC:\n",
    "            if self.getIV():\n",
    "                iv = self.__String_to_BitList(self.getIV())\n",
    "            else:\n",
    "                raise ValueError(\"For CBC mode, you must supply the Initial Value (IV) for ciphering\")\n",
    "\n",
    "        # Split the data into blocks, crypting each one seperately\n",
    "        i = 0\n",
    "        dict = {}\n",
    "        result = []\n",
    "        #cached = 0\n",
    "        #lines = 0\n",
    "        while i < len(data):\n",
    "            # Test code for caching encryption results\n",
    "            #lines += 1\n",
    "            #if dict.has_key(data[i:i+8]):\n",
    "                #print \"Cached result for: %s\" % data[i:i+8]\n",
    "            #\tcached += 1\n",
    "            #\tresult.append(dict[data[i:i+8]])\n",
    "            #\ti += 8\n",
    "            #\tcontinue\n",
    "\n",
    "            block = self.__String_to_BitList(data[i:i+8])\n",
    "\n",
    "            # Xor with IV if using CBC mode\n",
    "            if self.getMode() == CBC:\n",
    "                if crypt_type == des.ENCRYPT:\n",
    "                    block = list(map(lambda x, y: x ^ y, block, iv))\n",
    "                    #j = 0\n",
    "                    #while j < len(block):\n",
    "                    #\tblock[j] = block[j] ^ iv[j]\n",
    "                    #\tj += 1\n",
    "\n",
    "                processed_block = self.__des_crypt(block, crypt_type)\n",
    "\n",
    "                if crypt_type == des.DECRYPT:\n",
    "                    processed_block = list(map(lambda x, y: x ^ y, processed_block, iv))\n",
    "                    #j = 0\n",
    "                    #while j < len(processed_block):\n",
    "                    #\tprocessed_block[j] = processed_block[j] ^ iv[j]\n",
    "                    #\tj += 1\n",
    "                    iv = block\n",
    "                else:\n",
    "                    iv = processed_block\n",
    "            else:\n",
    "                processed_block = self.__des_crypt(block, crypt_type)\n",
    "\n",
    "\n",
    "            # Add the resulting crypted block to our list\n",
    "            #d = self.__BitList_to_String(processed_block)\n",
    "            #result.append(d)\n",
    "            result.append(self.__BitList_to_String(processed_block))\n",
    "            #dict[data[i:i+8]] = d\n",
    "            i += 8\n",
    "\n",
    "        # print \"Lines: %d, cached: %d\" % (lines, cached)\n",
    "\n",
    "        # Return the full crypted string\n",
    "        if _pythonMajorVersion < 3:\n",
    "            return ''.join(result)\n",
    "        else:\n",
    "            return bytes.fromhex('').join(result)\n",
    "\n",
    "    def encrypt(self, data, pad=None, padmode=None):\n",
    "        \"\"\"encrypt(data, [pad], [padmode]) -> bytes\n",
    "\n",
    "        data : Bytes to be encrypted\n",
    "        pad  : Optional argument for encryption padding. Must only be one byte\n",
    "        padmode : Optional argument for overriding the padding mode.\n",
    "\n",
    "        The data must be a multiple of 8 bytes and will be encrypted\n",
    "        with the already specified key. Data does not have to be a\n",
    "        multiple of 8 bytes if the padding character is supplied, or\n",
    "        the padmode is set to PAD_PKCS5, as bytes will then added to\n",
    "        ensure the be padded data is a multiple of 8 bytes.\n",
    "        \"\"\"\n",
    "        data = self._guardAgainstUnicode(data)\n",
    "        if pad is not None:\n",
    "            pad = self._guardAgainstUnicode(pad)\n",
    "        data = self._padData(data, pad, padmode)\n",
    "        return self.crypt(data, des.ENCRYPT)\n",
    "\n",
    "    def decrypt(self, data, pad=None, padmode=None):\n",
    "        \"\"\"decrypt(data, [pad], [padmode]) -> bytes\n",
    "\n",
    "        data : Bytes to be encrypted\n",
    "        pad  : Optional argument for decryption padding. Must only be one byte\n",
    "        padmode : Optional argument for overriding the padding mode.\n",
    "\n",
    "        The data must be a multiple of 8 bytes and will be decrypted\n",
    "        with the already specified key. In PAD_NORMAL mode, if the\n",
    "        optional padding character is supplied, then the un-encrypted\n",
    "        data will have the padding characters removed from the end of\n",
    "        the bytes. This pad removal only occurs on the last 8 bytes of\n",
    "        the data (last data block). In PAD_PKCS5 mode, the special\n",
    "        padding end markers will be removed from the data after decrypting.\n",
    "        \"\"\"\n",
    "        data = self._guardAgainstUnicode(data)\n",
    "        if pad is not None:\n",
    "            pad = self._guardAgainstUnicode(pad)\n",
    "        data = self.crypt(data, des.DECRYPT)\n",
    "        return self._unpadData(data, pad, padmode)\n",
    "\n",
    "\n",
    "\n",
    "    #############################################################################\n",
    "    # \t\t\t\tTriple DES\t\t\t\t    #\n",
    "    #############################################################################\n",
    "    class triple_des(_baseDes):\n",
    "    \"\"\"Triple DES encryption/decrytpion class\n",
    "\n",
    "    This algorithm uses the DES-EDE3 (when a 24 byte key is supplied) or\n",
    "    the DES-EDE2 (when a 16 byte key is supplied) encryption methods.\n",
    "    Supports ECB (Electronic Code Book) and CBC (Cypher Block Chaining) modes.\n",
    "\n",
    "    pyDes.des(key, [mode], [IV])\n",
    "\n",
    "    key  -> Bytes containing the encryption key, must be either 16 or\n",
    "            24 bytes long\n",
    "    mode -> Optional argument for encryption type, can be either pyDes.ECB\n",
    "        (Electronic Code Book), pyDes.CBC (Cypher Block Chaining)\n",
    "    IV   -> Optional Initial Value bytes, must be supplied if using CBC mode.\n",
    "        Must be 8 bytes in length.\n",
    "    pad  -> Optional argument, set the pad character (PAD_NORMAL) to use\n",
    "        during all encrypt/decrpt operations done with this instance.\n",
    "    padmode -> Optional argument, set the padding mode (PAD_NORMAL or\n",
    "        PAD_PKCS5) to use during all encrypt/decrpt operations done\n",
    "        with this instance.\n",
    "    \"\"\"\n",
    "    def __init__(self, key, mode=ECB, IV=None, pad=None, padmode=PAD_NORMAL):\n",
    "        _baseDes.__init__(self, mode, IV, pad, padmode)\n",
    "        self.setKey(key)\n",
    "\n",
    "    def setKey(self, key):\n",
    "        \"\"\"Will set the crypting key for this object. Either 16 or 24 bytes long.\"\"\"\n",
    "        self.key_size = 24  # Use DES-EDE3 mode\n",
    "        if len(key) != self.key_size:\n",
    "            if len(key) == 16: # Use DES-EDE2 mode\n",
    "                self.key_size = 16\n",
    "            else:\n",
    "                raise ValueError(\"Invalid triple DES key size. Key must be either 16 or 24 bytes long\")\n",
    "        if self.getMode() == CBC:\n",
    "            if not self.getIV():\n",
    "                # Use the first 8 bytes of the key\n",
    "                self._iv = key[:self.block_size]\n",
    "            if len(self.getIV()) != self.block_size:\n",
    "                raise ValueError(\"Invalid IV, must be 8 bytes in length\")\n",
    "        self.__key1 = des(key[:8], self._mode, self._iv,\n",
    "                  self._padding, self._padmode)\n",
    "        self.__key2 = des(key[8:16], self._mode, self._iv,\n",
    "                  self._padding, self._padmode)\n",
    "        if self.key_size == 16:\n",
    "            self.__key3 = self.__key1\n",
    "        else:\n",
    "            self.__key3 = des(key[16:], self._mode, self._iv,\n",
    "                      self._padding, self._padmode)\n",
    "        _baseDes.setKey(self, key)\n",
    "\n",
    "    # Override setter methods to work on all 3 keys.\n",
    "\n",
    "    def setMode(self, mode):\n",
    "        \"\"\"Sets the type of crypting mode, pyDes.ECB or pyDes.CBC\"\"\"\n",
    "        _baseDes.setMode(self, mode)\n",
    "        for key in (self.__key1, self.__key2, self.__key3):\n",
    "            key.setMode(mode)\n",
    "\n",
    "    def setPadding(self, pad):\n",
    "        \"\"\"setPadding() -> bytes of length 1. Padding character.\"\"\"\n",
    "        _baseDes.setPadding(self, pad)\n",
    "        for key in (self.__key1, self.__key2, self.__key3):\n",
    "            key.setPadding(pad)\n",
    "\n",
    "    def setPadMode(self, mode):\n",
    "        \"\"\"Sets the type of padding mode, pyDes.PAD_NORMAL or pyDes.PAD_PKCS5\"\"\"\n",
    "        _baseDes.setPadMode(self, mode)\n",
    "        for key in (self.__key1, self.__key2, self.__key3):\n",
    "            key.setPadMode(mode)\n",
    "\n",
    "    def setIV(self, IV):\n",
    "        \"\"\"Will set the Initial Value, used in conjunction with CBC mode\"\"\"\n",
    "        _baseDes.setIV(self, IV)\n",
    "        for key in (self.__key1, self.__key2, self.__key3):\n",
    "            key.setIV(IV)\n",
    "\n",
    "    def encrypt(self, data, pad=None, padmode=None):\n",
    "        \"\"\"encrypt(data, [pad], [padmode]) -> bytes\n",
    "\n",
    "        data : bytes to be encrypted\n",
    "        pad  : Optional argument for encryption padding. Must only be one byte\n",
    "        padmode : Optional argument for overriding the padding mode.\n",
    "\n",
    "        The data must be a multiple of 8 bytes and will be encrypted\n",
    "        with the already specified key. Data does not have to be a\n",
    "        multiple of 8 bytes if the padding character is supplied, or\n",
    "        the padmode is set to PAD_PKCS5, as bytes will then added to\n",
    "        ensure the be padded data is a multiple of 8 bytes.\n",
    "        \"\"\"\n",
    "        ENCRYPT = des.ENCRYPT\n",
    "        DECRYPT = des.DECRYPT\n",
    "        data = self._guardAgainstUnicode(data)\n",
    "        if pad is not None:\n",
    "            pad = self._guardAgainstUnicode(pad)\n",
    "        # Pad the data accordingly.\n",
    "        data = self._padData(data, pad, padmode)\n",
    "        if self.getMode() == CBC:\n",
    "            self.__key1.setIV(self.getIV())\n",
    "            self.__key2.setIV(self.getIV())\n",
    "            self.__key3.setIV(self.getIV())\n",
    "            i = 0\n",
    "            result = []\n",
    "            while i < len(data):\n",
    "                block = self.__key1.crypt(data[i:i+8], ENCRYPT)\n",
    "                block = self.__key2.crypt(block, DECRYPT)\n",
    "                block = self.__key3.crypt(block, ENCRYPT)\n",
    "                self.__key1.setIV(block)\n",
    "                self.__key2.setIV(block)\n",
    "                self.__key3.setIV(block)\n",
    "                result.append(block)\n",
    "                i += 8\n",
    "            if _pythonMajorVersion < 3:\n",
    "                return ''.join(result)\n",
    "            else:\n",
    "                return bytes.fromhex('').join(result)\n",
    "        else:\n",
    "            data = self.__key1.crypt(data, ENCRYPT)\n",
    "            data = self.__key2.crypt(data, DECRYPT)\n",
    "            return self.__key3.crypt(data, ENCRYPT)\n",
    "\n",
    "    def decrypt(self, data, pad=None, padmode=None):\n",
    "        \"\"\"decrypt(data, [pad], [padmode]) -> bytes\n",
    "\n",
    "        data : bytes to be encrypted\n",
    "        pad  : Optional argument for decryption padding. Must only be one byte\n",
    "        padmode : Optional argument for overriding the padding mode.\n",
    "\n",
    "        The data must be a multiple of 8 bytes and will be decrypted\n",
    "        with the already specified key. In PAD_NORMAL mode, if the\n",
    "        optional padding character is supplied, then the un-encrypted\n",
    "        data will have the padding characters removed from the end of\n",
    "        the bytes. This pad removal only occurs on the last 8 bytes of\n",
    "        the data (last data block). In PAD_PKCS5 mode, the special\n",
    "        padding end markers will be removed from the data after\n",
    "        decrypting, no pad character is required for PAD_PKCS5.\n",
    "        \"\"\"\n",
    "        ENCRYPT = des.ENCRYPT\n",
    "        DECRYPT = des.DECRYPT\n",
    "        data = self._guardAgainstUnicode(data)\n",
    "        if pad is not None:\n",
    "            pad = self._guardAgainstUnicode(pad)\n",
    "        if self.getMode() == CBC:\n",
    "            self.__key1.setIV(self.getIV())\n",
    "            self.__key2.setIV(self.getIV())\n",
    "            self.__key3.setIV(self.getIV())\n",
    "            i = 0\n",
    "            result = []\n",
    "            while i < len(data):\n",
    "                iv = data[i:i+8]\n",
    "                block = self.__key3.crypt(iv,    DECRYPT)\n",
    "                block = self.__key2.crypt(block, ENCRYPT)\n",
    "                block = self.__key1.crypt(block, DECRYPT)\n",
    "                self.__key1.setIV(iv)\n",
    "                self.__key2.setIV(iv)\n",
    "                self.__key3.setIV(iv)\n",
    "                result.append(block)\n",
    "                i += 8\n",
    "            if _pythonMajorVersion < 3:\n",
    "                data = ''.join(result)\n",
    "            else:\n",
    "                data = bytes.fromhex('').join(result)\n",
    "        else:\n",
    "            data = self.__key3.crypt(data, DECRYPT)\n",
    "            data = self.__key2.crypt(data, ENCRYPT)\n",
    "            data = self.__key1.crypt(data, DECRYPT)\n",
    "        return self._unpadData(data, pad, padmode)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1337f319",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sys import getsizeof\n",
    "getsizeof(\"Mynamejawadkhan\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "95e3e7a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "len(\"W3110D0N30GUY500\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0d94d0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "len(\"MynamejawadkhanMynamejawadkhan\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6fd9b650",
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import print_function\n",
    "\n",
    "import binascii\n",
    "import Crypto.Cipher.DES\n",
    "import itertools\n",
    "import sys\n",
    "import time\n",
    "\n",
    "# NB:\n",
    "# * hex keys are 64-bit hex-encoded ascii strings w/ parity bits\n",
    "# * bin keys are unhexlified hex keys\n",
    "\n",
    "DEFAULT_KEYLEN = 24\n",
    "\n",
    "def tell(x):\n",
    "  \"\"\"tell user on stderr\"\"\"\n",
    "  print(x, file = sys.stderr)\n",
    "\n",
    "def to_bin(x):\n",
    "  \"\"\"hex to bin\"\"\"\n",
    "  return binascii.unhexlify(x)\n",
    "\n",
    "def to_hex(x):\n",
    "  \"\"\"bin to hex\"\"\"\n",
    "  return binascii.hexlify(x)\n",
    "\n",
    "def hamming_weight(n):\n",
    "  \"\"\"hamming weight\"\"\"\n",
    "  return bin(n)[2:].count('1')\n",
    "\n",
    "def add_parity(n):\n",
    "  \"\"\"add parity bit\"\"\"\n",
    "  return n << 1 | (1 if hamming_weight(n) % 2 == 0 else 0)\n",
    "\n",
    "def decrypt(bin_k, bin_cipher):\n",
    "  \"\"\"decrypt w/ DES\"\"\"\n",
    "  return Crypto.Cipher.DES.new(bin_k).decrypt(bin_cipher)\n",
    "\n",
    "def encrypt(bin_k, bin_plain):\n",
    "  \"\"\"encrypt w/ DES\"\"\"\n",
    "  return Crypto.Cipher.DES.new(bin_k).encrypt(bin_plain)\n",
    "\n",
    "def nth_key(n):\n",
    "  \"\"\"nth hex key\"\"\"\n",
    "  return \"\".join([\n",
    "    \"{:02x}\".format(add_parity((n >> i * 7) & (2**7-1)))\n",
    "      for i in reversed(range(8))\n",
    "  ])\n",
    "\n",
    "def make_table(plain, keylen = DEFAULT_KEYLEN):\n",
    "    \"\"\"create lookup table from bin ciphertext to bin key(s)\"\"\"\n",
    "    table = {}\n",
    "    for k in itertools.imap(nth_key, xrange(2**keylen)):\n",
    "    bin_k = to_bin(k); bin_cipher = encrypt(bin_k, to_bin(plain))\n",
    "    table.setdefault(bin_cipher, []).append(bin_k)\n",
    "    return table\n",
    "\n",
    "def decryptions(cipher, keylen = DEFAULT_KEYLEN):\n",
    "  \"\"\"iterate over all possible (bin key, bin plain) decryptions\"\"\"\n",
    "  for k in itertools.imap(nth_key, xrange(2**keylen)):\n",
    "    bin_k = to_bin(k); bin_plain = decrypt(bin_k, to_bin(cipher))\n",
    "    yield (bin_k, bin_plain)\n",
    "\n",
    "def find_keypairs(plain, cipher, table, keylen = DEFAULT_KEYLEN):\n",
    "  \"\"\"iterate over all found key pairs\"\"\"\n",
    "  for (bin_k2, bin_c1) in decryptions(cipher, keylen):\n",
    "    k2 = to_hex(bin_k2)\n",
    "    for bin_k1 in table.get(bin_c1, []):\n",
    "        k1 = to_hex(bin_k1)\n",
    "        yield (k1, k2)\n",
    "\n",
    "def break_2des(plain, cipher, keylen = DEFAULT_KEYLEN):\n",
    "    \"\"\"break 2des w/ meet-in-the middle attack\"\"\"\n",
    "    tell(\"< plain   = {}\\n< cipher  = {}\".format(plain, cipher))\n",
    "    t1 = int(time.time())\n",
    "    table = make_table(plain, keylen)\n",
    "    t2 = int(time.time())\n",
    "    tell(\"< creating table took {:d} seconds\".format(t2 - t1))\n",
    "    t1 = int(time.time())\n",
    "    keypairs = list(find_keypairs(plain, cipher, table, keylen))\n",
    "    t2 = int(time.time())\n",
    "    tell(\"< finding pairs  took {:d} seconds\".format(t2 - t1))\n",
    "    return keypairs\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    keylen  = int(sys.argv[1])\n",
    "    if len(sys.argv) > 1:\n",
    "    else DEFAULT_KEYLEN\n",
    "    lines   = iter(line.rstrip(\"\\n\").lower() for line in sys.stdin)\n",
    "    for (plain, cipher) in itertools.izip(*[lines]*2):\n",
    "        for (k1, k2) in break_2des(plain, cipher, keylen):\n",
    "            tell(\"< k1      = {}\\n< k2      = {}\".format(k1, k2))\n",
    "            print(k1, k2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15046359",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad6826a1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "753080cd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f2b18069",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "65fff531",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a944b4ac",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6817ad5a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "470de4b4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "27cd8b01",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c05fde95",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92b2a7e1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e70b5997",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "011cb715",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
